export const user = [
  { id: 1, name: "Wireless Earbuds", category: "Electronics", price: 2499, inStock: true, rating: 4.3, image: "./" },
  { id: 2, name: "Smartphone X200", category: "Electronics", price: 18999, inStock: true, rating: 4.6, image: "https://via.placeholder.com/150" },
  { id: 3, name: "Laptop Pro 14", category: "Computers", price: 52999, inStock: false, rating: 4.7, image: "https://via.placeholder.com/150" },
  { id: 4, name: "Bluetooth Speaker", category: "Electronics", price: 3499, inStock: true, rating: 4.2, image: "https://via.placeholder.com/150" },
  { id: 5, name: "Men’s Running Shoes", category: "Fashion", price: 2999, inStock: true, rating: 4.1, image: "https://via.placeholder.com/150" },
  { id: 6, name: "Women’s Handbag", category: "Fashion", price: 1599, inStock: false, rating: 4.0, image: "https://via.placeholder.com/150" },
  { id: 7, name: "Casual T-Shirt", category: "Fashion", price: 799, inStock: true, rating: 3.9, image: "https://via.placeholder.com/150" },
  { id: 8, name: "Digital Watch", category: "Accessories", price: 1999, inStock: true, rating: 4.4, image: "https://via.placeholder.com/150" },
  { id: 9, name: "Backpack Bag", category: "Accessories", price: 1299, inStock: true, rating: 4.2, image: "https://via.placeholder.com/150" },
  { id: 10, name: "Gaming Keyboard", category: "Computers", price: 2299, inStock: true, rating: 4.5, image: "https://via.placeholder.com/150" },
  { id: 11, name: "Gaming Mouse", category: "Computers", price: 1299, inStock: true, rating: 4.3, image: "https://via.placeholder.com/150" },
  { id: 12, name: "Office Chair", category: "Furniture", price: 6499, inStock: false, rating: 4.1, image: "https://via.placeholder.com/150" },
  { id: 13, name: "Study Desk", category: "Furniture", price: 4599, inStock: true, rating: 4.0, image: "https://via.placeholder.com/150" },
  { id: 14, name: "Water Bottle", category: "Home", price: 499, inStock: true, rating: 3.8, image: "https://via.placeholder.com/150" },
  { id: 15, name: "Cooking Pan Set", category: "Home", price: 1799, inStock: true, rating: 4.3, image: "https://via.placeholder.com/150" },
  { id: 16, name: "LED Table Lamp", category: "Home", price: 899, inStock: false, rating: 4.2, image: "https://via.placeholder.com/150" },
  { id: 17, name: "Sports Jacket", category: "Fashion", price: 2499, inStock: true, rating: 4.5, image: "https://via.placeholder.com/150" },
  { id: 18, name: "Yoga Mat", category: "Sports", price: 699, inStock: true, rating: 4.1, image: "https://via.placeholder.com/150" },
  { id: 19, name: "Cricket Bat", category: "Sports", price: 2299, inStock: true, rating: 4.4, image: "https://via.placeholder.com/150" },
  { id: 20, name: "Football", category: "Sports", price: 1199, inStock: true, rating: 4.2, image: "https://via.placeholder.com/150" },
  { id: 21, name: "Bookshelf", category: "Furniture", price: 3899, inStock: true, rating: 4.3, image: "https://via.placeholder.com/150" },
  { id: 22, name: "Perfume Bottle", category: "Beauty", price: 1299, inStock: true, rating: 4.0, image: "https://via.placeholder.com/150" },
  { id: 23, name: "Makeup Kit", category: "Beauty", price: 2499, inStock: false, rating: 4.1, image: "https://via.placeholder.com/150" },
  { id: 24, name: "Sunglasses", category: "Accessories", price: 899, inStock: true, rating: 4.5, image: "https://via.placeholder.com/150" }
];
